export const Records = [
  {
    Intern: "John Doe",
    Company: "Tech Solutions",
    Department: "Engineering",
    StartDate: "Jan 01, 2023",
    EndDate: "Jun 30, 2023",
    TotalHours: 500,
    Status: "Completed",
  },
  {
    Intern: "Jane Smith",
    Company: "Innovatech",
    Department: "Marketing",
    StartDate: "Feb 15, 2023",
    EndDate: "Aug 15, 2023",
    TotalHours: 600,
    Status: "Ongoing",
  },
  {
    Intern: "Alice Johnson",
    Company: "Creative Minds",
    Department: "Design",
    StartDate: "Mar 01, 2023",
    EndDate: "Sep 01, 2023",
    TotalHours: 450,
    Status: "Pending",
  },
  {
    Intern: "Bob Brown",
    Company: "Future Tech",
    Department: "Development",
    StartDate: "Apr 01, 2023",
    EndDate: "Oct 01, 2023",
    TotalHours: 480,
    Status: "Ongoing",
  },
  {
    Intern: "Charlie Davis",
    Company: "NextGen",
    Department: "Research",
    StartDate: "May 01, 2023",
    EndDate: "Nov 01, 2023",
    TotalHours: 490,
    Status: "Completed",
  },
  {
    Intern: "Diana Evans",
    Company: "Alpha Corp",
    Department: "HR",
    StartDate: "Jun 01, 2023",
    EndDate: "Dec 01, 2023",
    TotalHours: 500,
    Status: "Pending",
  },
  {
    Intern: "Ethan Foster",
    Company: "Beta Inc",
    Department: "Finance",
    StartDate: "Jul 01, 2023",
    EndDate: "Jan 01, 2024",
    TotalHours: 510,
    Status: "Ongoing",
  },
  {
    Intern: "Fiona Green",
    Company: "Gamma LLC",
    Department: "Sales",
    StartDate: "Aug 01, 2023",
    EndDate: "Feb 01, 2024",
    TotalHours: 520,
    Status: "Completed",
  },
  {
    Intern: "George Harris",
    Company: "Delta Ltd",
    Department: "Support",
    StartDate: "Sep 01, 2023",
    EndDate: "Mar 01, 2024",
    TotalHours: 530,
    Status: "Pending",
  },
  {
    Intern: "Hannah White",
    Company: "Epsilon Co",
    Department: "Logistics",
    StartDate: "Oct 01, 2023",
    EndDate: "Apr 01, 2024",
    TotalHours: 540,
    Status: "Ongoing",
  },
  {
    Intern: "Ian King",
    Company: "Zeta Group",
    Department: "Operations",
    StartDate: "Nov 01, 2023",
    EndDate: "May 01, 2024",
    TotalHours: 550,
    Status: "Completed",
  },
  {
    Intern: "Jack Lee",
    Company: "Eta Enterprises",
    Department: "IT",
    StartDate: "Dec 01, 2023",
    EndDate: "Jun 01, 2024",
    TotalHours: 560,
    Status: "Pending",
  },
  {
    Intern: "Karen Martinez",
    Company: "Theta Solutions",
    Department: "Engineering",
    StartDate: "Jan 01, 2024",
    EndDate: "Jul 01, 2024",
    TotalHours: 570,
    Status: "Ongoing",
  },
  {
    Intern: "Liam Nelson",
    Company: "Iota Innovations",
    Department: "Marketing",
    StartDate: "Feb 01, 2024",
    EndDate: "Aug 01, 2024",
    TotalHours: 580,
    Status: "Completed",
  },
  {
    Intern: "Mia Perez",
    Company: "Kappa Technologies",
    Department: "Design",
    StartDate: "Mar 01, 2024",
    EndDate: "Sep 01, 2024",
    TotalHours: 590,
    Status: "Pending",
  },
  {
    Intern: "Noah Quinn",
    Company: "Lambda Systems",
    Department: "Development",
    StartDate: "Apr 01, 2024",
    EndDate: "Oct 01, 2024",
    TotalHours: 600,
    Status: "Ongoing",
  },
  {
    Intern: "Olivia Roberts",
    Company: "Mu Networks",
    Department: "Research",
    StartDate: "May 01, 2024",
    EndDate: "Nov 01, 2024",
    TotalHours: 610,
    Status: "Completed",
  },
  {
    Intern: "Paul Scott",
    Company: "Nu Enterprises",
    Department: "HR",
    StartDate: "Jun 01, 2024",
    EndDate: "Dec 01, 2024",
    TotalHours: 620,
    Status: "Pending",
  },
  {
    Intern: "Quinn Taylor",
    Company: "Xi Corp",
    Department: "Finance",
    StartDate: "Jul 01, 2024",
    EndDate: "Jan 01, 2025",
    TotalHours: 630,
    Status: "Ongoing",
  },
  {
    Intern: "Rachel Walker",
    Company: "Omicron Inc",
    Department: "Sales",
    StartDate: "Aug 01, 2024",
    EndDate: "Feb 01, 2025",
    TotalHours: 640,
    Status: "Completed",
  },
  {
    Intern: "Samuel Young",
    Company: "Pi LLC",
    Department: "Support",
    StartDate: "Sep 01, 2024",
    EndDate: "Mar 01, 2025",
    TotalHours: 650,
    Status: "Pending",
  },
  {
    Intern: "Tina Adams",
    Company: "Rho Ltd",
    Department: "Logistics",
    StartDate: "Oct 01, 2024",
    EndDate: "Apr 01, 2025",
    TotalHours: 660,
    Status: "Ongoing",
  },
  {
    Intern: "Umar Brown",
    Company: "Sigma Co",
    Department: "Operations",
    StartDate: "Nov 01, 2024",
    EndDate: "May 01, 2025",
    TotalHours: 670,
    Status: "Completed",
  },
  {
    Intern: "Vera Clark",
    Company: "Tau Group",
    Department: "IT",
    StartDate: "Dec 01, 2024",
    EndDate: "Jun 01, 2025",
    TotalHours: 680,
    Status: "Pending",
  },
  {
    Intern: "Will Davis",
    Company: "Upsilon Enterprises",
    Department: "Engineering",
    StartDate: "Jan 01, 2025",
    EndDate: "Jul 01, 2025",
    TotalHours: 690,
    Status: "Ongoing",
  },
  {
    Intern: "Xena Evans",
    Company: "Phi Solutions",
    Department: "Marketing",
    StartDate: "Feb 01, 2025",
    EndDate: "Aug 01, 2025",
    TotalHours: 700,
    Status: "Completed",
  },
  {
    Intern: "Yara Foster",
    Company: "Chi Innovations",
    Department: "Design",
    StartDate: "Mar 01, 2025",
    EndDate: "Sep 01, 2025",
    TotalHours: 710,
    Status: "Pending",
  },
  {
    Intern: "Zane Green",
    Company: "Psi Technologies",
    Department: "Development",
    StartDate: "Apr 01, 2025",
    EndDate: "Oct 01, 2025",
    TotalHours: 720,
    Status: "Ongoing",
  },
  {
    Intern: "Amy Harris",
    Company: "Omega Systems",
    Department: "Research",
    StartDate: "May 01, 2025",
    EndDate: "Nov 01, 2025",
    TotalHours: 730,
    Status: "Completed",
  },
  {
    Intern: "Brian King",
    Company: "Alpha Corp",
    Department: "HR",
    StartDate: "Jun 01, 2025",
    EndDate: "Dec 01, 2025",
    TotalHours: 740,
    Status: "Pending",
  },
  {
    Intern: "Cathy Lee",
    Company: "Beta Inc",
    Department: "Finance",
    StartDate: "Jul 01, 2025",
    EndDate: "Jan 01, 2026",
    TotalHours: 750,
    Status: "Ongoing",
  },
  {
    Intern: "David Martinez",
    Company: "Gamma LLC",
    Department: "Sales",
    StartDate: "Aug 01, 2025",
    EndDate: "Feb 01, 2026",
    TotalHours: 760,
    Status: "Completed",
  },
  {
    Intern: "Ella Nelson",
    Company: "Delta Ltd",
    Department: "Support",
    StartDate: "Sep 01, 2025",
    EndDate: "Mar 01, 2026",
    TotalHours: 770,
    Status: "Pending",
  },
  {
    Intern: "Frank Perez",
    Company: "Epsilon Co",
    Department: "Logistics",
    StartDate: "Oct 01, 2025",
    EndDate: "Apr 01, 2026",
    TotalHours: 780,
    Status: "Ongoing",
  },
  {
    Intern: "Grace Quinn",
    Company: "Zeta Group",
    Department: "Operations",
    StartDate: "Nov 01, 2025",
    EndDate: "May 01, 2026",
    TotalHours: 790,
    Status: "Completed",
  },
  {
    Intern: "Henry Roberts",
    Company: "Eta Enterprises",
    Department: "IT",
    StartDate: "Dec 01, 2025",
    EndDate: "Jun 01, 2026",
    TotalHours: 800,
    Status: "Pending",
  },
  {
    Intern: "Ivy Scott",
    Company: "Theta Solutions",
    Department: "Engineering",
    StartDate: "Jan 01, 2026",
    EndDate: "Jul 01, 2026",
    TotalHours: 810,
    Status: "Ongoing",
  },
  {
    Intern: "Jack Taylor",
    Company: "Iota Innovations",
    Department: "Marketing",
    StartDate: "Feb 01, 2026",
    EndDate: "Aug 01, 2026",
    TotalHours: 820,
    Status: "Completed",
  },
  {
    Intern: "Kara Walker",
    Company: "Kappa Technologies",
    Department: "Design",
    StartDate: "Mar 01, 2026",
    EndDate: "Sep 01, 2026",
    TotalHours: 830,
    Status: "Pending",
  },
  {
    Intern: "Liam Young",
    Company: "Lambda Systems",
    Department: "Development",
    StartDate: "Apr 01, 2026",
    EndDate: "Oct 01, 2026",
    TotalHours: 840,
    Status: "Ongoing",
  },
  {
    Intern: "Mia Adams",
    Company: "Mu Networks",
    Department: "Research",
    StartDate: "May 01, 2026",
    EndDate: "Nov 01, 2026",
    TotalHours: 850,
    Status: "Completed",
  },
  {
    Intern: "Noah Brown",
    Company: "Nu Enterprises",
    Department: "HR",
    StartDate: "Jun 01, 2026",
    EndDate: "Dec 01, 2026",
    TotalHours: 860,
    Status: "Pending",
  },
  {
    Intern: "Olivia Clark",
    Company: "Xi Corp",
    Department: "Finance",
    StartDate: "Jul 01, 2026",
    EndDate: "Jan 01, 2027",
    TotalHours: 870,
    Status: "Ongoing",
  },
  {
    Intern: "Paul Davis",
    Company: "Omicron Inc",
    Department: "Sales",
    StartDate: "Aug 01, 2026",
    EndDate: "Feb 01, 2027",
    TotalHours: 880,
    Status: "Completed",
  },
  {
    Intern: "Quinn Evans",
    Company: "Pi LLC",
    Department: "Support",
    StartDate: "Sep 01, 2026",
    EndDate: "Mar 01, 2027",
    TotalHours: 890,
    Status: "Pending",
  },
  {
    Intern: "Rachel Foster",
    Company: "Rho Ltd",
    Department: "Logistics",
    StartDate: "Oct 01, 2026",
    EndDate: "Apr 01, 2027",
    TotalHours: 900,
    Status: "Ongoing",
  },
  {
    Intern: "Samuel Green",
    Company: "Sigma Co",
    Department: "Operations",
    StartDate: "Nov 01, 2026",
    EndDate: "May 01, 2027",
    TotalHours: 910,
    Status: "Completed",
  },
  {
    Intern: "Tina Harris",
    Company: "Tau Group",
    Department: "IT",
    StartDate: "Dec 01, 2026",
    EndDate: "Jun 01, 2027",
    TotalHours: 920,
    Status: "Pending",
  },
];
